In [41]:
import pandas as pd
dframe = pd.read_csv('ai_student_impact_dataset (1).csv')
dframe
print(dframe.head())

print(dframe.iloc[1])
dframe.iloc[2:6, [0,1,2,5,9]]

   Student_ID Major_Category Year_of_Study  Pre_Semester_GPA  \
0      100001     Humanities        Senior             2.418
1      100002        Medical        Junior             3.821
2      100003       Business      Freshman             3.398
3      100004       Business        Senior             3.789
4      100005           STEM     Sophomore             3.635

   Weekly_GenAI_Hours           Primary_Use_Case Prompt_Engineering_Skill  \
0               23.31       Copywriting/Drafting                 Beginner
1                1.12                   Ideation                 Advanced
2               21.26        Summarizing_Reading                 Beginner
3                1.82       Copywriting/Drafting             Intermediate
4                9.29  Debugging/Troubleshooting                 Advanced

   Tool_Diversity  Paid_Subscription  Traditional_Study_Hours  \
0               1               True                     8.13
1               5              False                    16.65
2               2              False                    10.35
3               4              False                    15.23
4               4              False                    12.55

   Perceived_AI_Dependency   Institutional_Policy  Anxiety_Level_During_Exams  \
0                        5  Allowed_With_Citation                           6
1                        3  Allowed_With_Citation                           9
2                        5             Strict_Ban                           9
3                        2  Allowed_With_Citation                           2
4                        4  Allowed_With_Citation                           4

   Post_Semester_GPA  Skill_Retention_Score Burnout_Risk_Level
0              2.393                  86.44               High
1              3.696                  69.39                Low
2              3.499                  73.93             Medium
3              4.000                  63.58             Medium
4              3.798                 100.00             Medium
Student_ID                                   100002
Major_Category                              Medical
Year_of_Study                                Junior
Pre_Semester_GPA                              3.821
Weekly_GenAI_Hours                             1.12
Primary_Use_Case                           Ideation
Prompt_Engineering_Skill                   Advanced
Tool_Diversity                                    5
Paid_Subscription                             False
Traditional_Study_Hours                       16.65
Perceived_AI_Dependency                           3
Institutional_Policy          Allowed_With_Citation
Anxiety_Level_During_Exams                        9
Post_Semester_GPA                             3.696
Skill_Retention_Score                         69.39
Burnout_Risk_Level                              Low
Name: 1, dtype: object

,Student_ID,Major_Category,Year_of_Study,Primary_Use_Case,Traditional_Study_Hours
2,100003,Business,Freshman,Summarizing_Reading,10.35
3,100004,Business,Senior,Copywriting/Drafting,15.23
4,100005,STEM,Sophomore,Debugging/Troubleshooting,12.55
5,100006,STEM,Junior,Debugging/Troubleshooting,14.19

In [34]:
dframe.index

RangeIndex(start=0, stop=50000, step=1)

In [35]:
dframe

,Student_ID,Major_Category,Year_of_Study,Pre_Semester_GPA,Weekly_GenAI_Hours,Primary_Use_Case,Prompt_Engineering_Skill,Tool_Diversity,Paid_Subscription,Traditional_Study_Hours,Perceived_AI_Dependency,Institutional_Policy,Anxiety_Level_During_Exams,Post_Semester_GPA,Skill_Retention_Score,Burnout_Risk_Level
0,100001,Humanities,Senior,2.418,23.31,Copywriting/Drafting,Beginner,1,True,8.13,5,Allowed_With_Citation,6,2.393,86.44,High
1,100002,Medical,Junior,3.821,1.12,Ideation,Advanced,5,False,16.65,3,Allowed_With_Citation,9,3.696,69.39,Low
2,100003,Business,Freshman,3.398,21.26,Summarizing_Reading,Beginner,2,False,10.35,5,Strict_Ban,9,3.499,73.93,Medium
3,100004,Business,Senior,3.789,1.82,Copywriting/Drafting,Intermediate,4,False,15.23,2,Allowed_With_Citation,2,4.000,63.58,Medium
4,100005,STEM,Sophomore,3.635,9.29,Debugging/Troubleshooting,Advanced,4,False,12.55,4,Allowed_With_Citation,4,3.798,100.00,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,149996,Business,Senior,2.899,12.16,Copywriting/Drafting,Beginner,2,False,13.36,2,Allowed_With_Citation,2,3.584,66.16,High
49996,149997,STEM,Senior,2.870,2.51,Copywriting/Drafting,Intermediate,1,False,4.67,3,Actively_Encouraged,3,3.096,81.62,Medium
49997,149998,Business,Senior,3.177,15.87,Summarizing_Reading,Advanced,5,True,3.92,4,Allowed_With_Citation,5,3.605,97.21,High
49998,149999,Business,Junior,3.398,19.91,Debugging/Troubleshooting,Intermediate,5,False,7.10,5,Allowed_With_Citation,3,3.527,84.12,Medium
49999,150000,Arts,Sophomore,3.242,3.30,Copywriting/Drafting,Beginner,1,False,3.93,2,Allowed_With_Citation,6,3.261,76.16,Low

In [45]:
dframe.set_index("Major_Category")

,Student_ID,Year_of_Study,Pre_Semester_GPA,Weekly_GenAI_Hours,Primary_Use_Case,Prompt_Engineering_Skill,Tool_Diversity,Paid_Subscription,Traditional_Study_Hours,Perceived_AI_Dependency,Institutional_Policy,Anxiety_Level_During_Exams,Post_Semester_GPA,Skill_Retention_Score,Burnout_Risk_Level
Major_Category,,,,,,,,,,,,,,,
Humanities,100001,Senior,2.418,23.31,Copywriting/Drafting,Beginner,1,True,8.13,5,Allowed_With_Citation,6,2.393,86.44,High
Medical,100002,Junior,3.821,1.12,Ideation,Advanced,5,False,16.65,3,Allowed_With_Citation,9,3.696,69.39,Low
Business,100003,Freshman,3.398,21.26,Summarizing_Reading,Beginner,2,False,10.35,5,Strict_Ban,9,3.499,73.93,Medium
Business,100004,Senior,3.789,1.82,Copywriting/Drafting,Intermediate,4,False,15.23,2,Allowed_With_Citation,2,4.000,63.58,Medium
STEM,100005,Sophomore,3.635,9.29,Debugging/Troubleshooting,Advanced,4,False,12.55,4,Allowed_With_Citation,4,3.798,100.00,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Business,149996,Senior,2.899,12.16,Copywriting/Drafting,Beginner,2,False,13.36,2,Allowed_With_Citation,2,3.584,66.16,High
STEM,149997,Senior,2.870,2.51,Copywriting/Drafting,Intermediate,1,False,4.67,3,Actively_Encouraged,3,3.096,81.62,Medium
Business,149998,Senior,3.177,15.87,Summarizing_Reading,Advanced,5,True,3.92,4,Allowed_With_Citation,5,3.605,97.21,High
Business,149999,Junior,3.398,19.91,Debugging/Troubleshooting,Intermediate,5,False,7.10,5,Allowed_With_Citation,3,3.527,84.12,Medium
Arts,150000,Sophomore,3.242,3.30,Copywriting/Drafting,Beginner,1,False,3.93,2,Allowed_With_Citation,6,3.261,76.16,Low

In [91]:
dframe.loc[50:70, ['Major_Category','Year_of_Study','Pre_Semester_GPA']]

   Major_Category Year_of_Study  Pre_Semester_GPA
50        Medical     Sophomore             3.577
51           Arts        Senior             2.433
52        Medical     Sophomore             2.958
53        Medical        Senior             3.732
54       Business        Junior             3.148
55        Medical        Senior             3.429
56           STEM        Junior             3.837
57           STEM     Sophomore             3.249
58           STEM        Junior             3.015
59     Humanities     Sophomore             3.167
60     Humanities     Sophomore             3.697
61           STEM      Freshman             3.463
62           Arts        Senior             2.164
63     Humanities      Freshman             2.771
64           STEM      Graduate             3.569
65       Business      Freshman             3.074
66           STEM      Graduate             3.329
67           Arts      Graduate             3.606
68           STEM     Sophomore             3.645
69        Medical      Graduate             2.838
70           Arts      Graduate             3.047

In [59]:
dframe.columns

Index(['Student_ID', 'Major_Category', 'Year_of_Study', 'Pre_Semester_GPA',
       'Weekly_GenAI_Hours', 'Primary_Use_Case', 'Prompt_Engineering_Skill',
       'Tool_Diversity', 'Paid_Subscription', 'Traditional_Study_Hours',
       'Perceived_AI_Dependency', 'Institutional_Policy',
       'Anxiety_Level_During_Exams', 'Post_Semester_GPA',
       'Skill_Retention_Score', 'Burnout_Risk_Level'],
      dtype='object')

In [77]:
dframe.loc[:, 'Tool_Diversity']== 5 
#dframe.loc[:,'Post_Semester_GPA']==4.00

0        False
1         True
2        False
3        False
4        False
         ...
49995    False
49996    False
49997     True
49998     True
49999    False
Name: Tool_Diversity, Length: 50000, dtype: bool

In [84]:
filt = dframe['Tool_Diversity']== 5 
dframe.loc[filt]

,Student_ID,Major_Category,Year_of_Study,Pre_Semester_GPA,Weekly_GenAI_Hours,Primary_Use_Case,Prompt_Engineering_Skill,Tool_Diversity,Paid_Subscription,Traditional_Study_Hours,Perceived_AI_Dependency,Institutional_Policy,Anxiety_Level_During_Exams,Post_Semester_GPA,Skill_Retention_Score,Burnout_Risk_Level
1,100002,Medical,Junior,3.821,1.12,Ideation,Advanced,5,False,16.65,3,Allowed_With_Citation,9,3.696,69.39,Low
6,100007,STEM,Freshman,3.622,31.41,Summarizing_Reading,Advanced,5,True,13.11,8,Allowed_With_Citation,7,4.000,67.97,Medium
26,100027,STEM,Sophomore,3.338,18.62,Debugging/Troubleshooting,Advanced,5,True,14.29,6,Allowed_With_Citation,2,3.822,82.36,Medium
33,100034,Medical,Senior,3.148,5.56,Summarizing_Reading,Intermediate,5,False,9.89,2,Allowed_With_Citation,1,3.335,89.14,Medium
86,100087,Business,Graduate,3.033,9.65,Ideation,Intermediate,5,True,2.81,2,Strict_Ban,5,3.216,93.82,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49966,149967,Medical,Junior,2.921,22.68,Summarizing_Reading,Advanced,5,True,4.56,7,Allowed_With_Citation,4,3.150,71.18,High
49970,149971,STEM,Freshman,3.219,10.48,Copywriting/Drafting,Intermediate,5,False,8.44,3,Allowed_With_Citation,1,3.343,74.77,Low
49984,149985,Business,Senior,3.548,2.76,Copywriting/Drafting,Advanced,5,False,9.19,3,Allowed_With_Citation,6,3.721,93.32,Low
49997,149998,Business,Senior,3.177,15.87,Summarizing_Reading,Advanced,5,True,3.92,4,Allowed_With_Citation,5,3.605,97.21,High
49998,149999,Business,Junior,3.398,19.91,Debugging/Troubleshooting,Intermediate,5,False,7.10,5,Allowed_With_Citation,3,3.527,84.12,Medium

In [85]:
filt = dframe['Tool_Diversity']== 5 
dframe.loc[filt].head()

,Student_ID,Major_Category,Year_of_Study,Pre_Semester_GPA,Weekly_GenAI_Hours,Primary_Use_Case,Prompt_Engineering_Skill,Tool_Diversity,Paid_Subscription,Traditional_Study_Hours,Perceived_AI_Dependency,Institutional_Policy,Anxiety_Level_During_Exams,Post_Semester_GPA,Skill_Retention_Score,Burnout_Risk_Level
1,100002,Medical,Junior,3.821,1.12,Ideation,Advanced,5,False,16.65,3,Allowed_With_Citation,9,3.696,69.39,Low
6,100007,STEM,Freshman,3.622,31.41,Summarizing_Reading,Advanced,5,True,13.11,8,Allowed_With_Citation,7,4.000,67.97,Medium
26,100027,STEM,Sophomore,3.338,18.62,Debugging/Troubleshooting,Advanced,5,True,14.29,6,Allowed_With_Citation,2,3.822,82.36,Medium
33,100034,Medical,Senior,3.148,5.56,Summarizing_Reading,Intermediate,5,False,9.89,2,Allowed_With_Citation,1,3.335,89.14,Medium
86,100087,Business,Graduate,3.033,9.65,Ideation,Intermediate,5,True,2.81,2,Strict_Ban,5,3.216,93.82,High

In [86]:
filt = dframe['Tool_Diversity']== 5 
dframe.loc[filt].sort_index().head()

,Student_ID,Major_Category,Year_of_Study,Pre_Semester_GPA,Weekly_GenAI_Hours,Primary_Use_Case,Prompt_Engineering_Skill,Tool_Diversity,Paid_Subscription,Traditional_Study_Hours,Perceived_AI_Dependency,Institutional_Policy,Anxiety_Level_During_Exams,Post_Semester_GPA,Skill_Retention_Score,Burnout_Risk_Level
1,100002,Medical,Junior,3.821,1.12,Ideation,Advanced,5,False,16.65,3,Allowed_With_Citation,9,3.696,69.39,Low
6,100007,STEM,Freshman,3.622,31.41,Summarizing_Reading,Advanced,5,True,13.11,8,Allowed_With_Citation,7,4.000,67.97,Medium
26,100027,STEM,Sophomore,3.338,18.62,Debugging/Troubleshooting,Advanced,5,True,14.29,6,Allowed_With_Citation,2,3.822,82.36,Medium
33,100034,Medical,Senior,3.148,5.56,Summarizing_Reading,Intermediate,5,False,9.89,2,Allowed_With_Citation,1,3.335,89.14,Medium
86,100087,Business,Graduate,3.033,9.65,Ideation,Intermediate,5,True,2.81,2,Strict_Ban,5,3.216,93.82,High

In [87]:
filt = dframe['Tool_Diversity']== 5 
dframe.loc[filt].sort_index(ascending=False).head()

,Student_ID,Major_Category,Year_of_Study,Pre_Semester_GPA,Weekly_GenAI_Hours,Primary_Use_Case,Prompt_Engineering_Skill,Tool_Diversity,Paid_Subscription,Traditional_Study_Hours,Perceived_AI_Dependency,Institutional_Policy,Anxiety_Level_During_Exams,Post_Semester_GPA,Skill_Retention_Score,Burnout_Risk_Level
49998,149999,Business,Junior,3.398,19.91,Debugging/Troubleshooting,Intermediate,5,False,7.10,5,Allowed_With_Citation,3,3.527,84.12,Medium
49997,149998,Business,Senior,3.177,15.87,Summarizing_Reading,Advanced,5,True,3.92,4,Allowed_With_Citation,5,3.605,97.21,High
49984,149985,Business,Senior,3.548,2.76,Copywriting/Drafting,Advanced,5,False,9.19,3,Allowed_With_Citation,6,3.721,93.32,Low
49970,149971,STEM,Freshman,3.219,10.48,Copywriting/Drafting,Intermediate,5,False,8.44,3,Allowed_With_Citation,1,3.343,74.77,Low
49966,149967,Medical,Junior,2.921,22.68,Summarizing_Reading,Advanced,5,True,4.56,7,Allowed_With_Citation,4,3.150,71.18,High

In [95]:
filt = (dframe['Tool_Diversity']== 5) |  (dframe['Prompt_Engineering_Skill']== 'Intermediate')
dframe.loc[filt].sort_index(ascending=True).tail(50)

,Student_ID,Major_Category,Year_of_Study,Pre_Semester_GPA,Weekly_GenAI_Hours,Primary_Use_Case,Prompt_Engineering_Skill,Tool_Diversity,Paid_Subscription,Traditional_Study_Hours,Perceived_AI_Dependency,Institutional_Policy,Anxiety_Level_During_Exams,Post_Semester_GPA,Skill_Retention_Score,Burnout_Risk_Level
49901,149902,Business,Junior,2.789,6.61,Debugging/Troubleshooting,Intermediate,4,False,11.55,4,Actively_Encouraged,5,2.877,86.73,High
49905,149906,Business,Junior,1.862,4.31,Summarizing_Reading,Intermediate,3,False,1.00,4,Allowed_With_Citation,5,1.977,81.86,High
49906,149907,STEM,Junior,2.892,4.50,Copywriting/Drafting,Intermediate,4,False,4.83,4,Strict_Ban,7,2.885,51.63,Medium
49908,149909,STEM,Junior,3.624,36.73,Ideation,Intermediate,2,True,4.33,8,Strict_Ban,10,3.826,72.76,High
49909,149910,Humanities,Junior,3.775,0.18,Ideation,Intermediate,2,False,2.99,3,Actively_Encouraged,5,3.929,69.50,Medium
49910,149911,Business,Junior,3.008,3.34,Ideation,Intermediate,3,True,10.13,1,Allowed_With_Citation,7,3.011,93.57,High
49911,149912,Humanities,Freshman,3.058,0.54,Copywriting/Drafting,Intermediate,5,False,8.29,1,Allowed_With_Citation,3,3.061,61.46,Low
49914,149915,Medical,Freshman,2.098,13.90,Summarizing_Reading,Intermediate,3,True,1.19,2,Allowed_With_Citation,3,2.064,51.12,High
49915,149916,Humanities,Junior,2.057,2.73,Summarizing_Reading,Intermediate,4,False,18.21,1,Allowed_With_Citation,2,2.461,64.00,Medium
49918,149919,STEM,Sophomore,2.132,1.31,Debugging/Troubleshooting,Intermediate,3,False,14.23,1,Actively_Encouraged,6,2.161,90.26,Low
49922,149923,STEM,Graduate,2.598,14.95,Debugging/Troubleshooting,Intermediate,4,False,17.83,7,Actively_Encouraged,5,3.024,78.89,Medium
49923,149924,Business,Senior,3.032,11.11,Direct_Answer_Generation,Intermediate,3,True,15.82,4,Strict_Ban,6,3.285,85.36,Medium
49925,149926,STEM,Sophomore,3.391,4.12,Direct_Answer_Generation,Intermediate,3,True,8.14,4,Allowed_With_Citation,3,3.526,61.95,Medium
49926,149927,Humanities,Senior,3.617,5.59,Ideation,Intermediate,1,False,6.42,3,Allowed_With_Citation,7,3.905,76.69,Low
49928,149929,Business,Sophomore,2.040,0.56,Summarizing_Reading,Advanced,5,False,13.51,1,Allowed_With_Citation,3,2.110,74.72,Medium
49929,149930,STEM,Sophomore,3.088,12.48,Summarizing_Reading,Intermediate,4,True,8.12,5,Actively_Encouraged,6,3.479,91.05,Medium
49930,149931,STEM,Junior,3.822,2.28,Summarizing_Reading,Intermediate,4,True,13.90,4,Strict_Ban,3,4.000,63.91,Low
49932,149933,Business,Senior,2.458,4.58,Ideation,Intermediate,2,True,8.94,2,Allowed_With_Citation,6,2.817,79.16,Low
49933,149934,Arts,Senior,3.064,6.66,Copywriting/Drafting,Intermediate,1,False,1.00,2,Actively_Encouraged,2,3.092,83.48,Low
49934,149935,Business,Sophomore,2.378,20.90,Ideation,Intermediate,4,False,13.44,7,Allowed_With_Citation,3,2.552,93.08,High
49935,149936,Medical,Graduate,3.040,5.34,Debugging/Troubleshooting,Intermediate,5,False,11.49,4,Allowed_With_Citation,6,3.398,68.64,High
49937,149938,Business,Freshman,3.113,40.00,Direct_Answer_Generation,Intermediate,2,True,14.87,9,Allowed_With_Citation,7,2.875,23.86,High
49939,149940,Business,Junior,3.184,4.80,Ideation,Intermediate,4,False,15.67,3,Strict_Ban,5,3.523,100.00,Medium
49941,149942,Humanities,Freshman,3.288,9.39,Summarizing_Reading,Intermediate,4,True,1.00,3,Strict_Ban,2,3.244,83.33,Medium
49943,149944,Arts,Senior,3.066,2.95,Copywriting/Drafting,Intermediate,2,False,4.81,3,Allowed_With_Citation,4,3.260,80.09,High
49945,149946,STEM,Sophomore,2.027,10.41,Debugging/Troubleshooting,Intermediate,4,True,14.85,5,Allowed_With_Citation,5,2.378,74.83,High
49950,149951,Humanities,Freshman,3.848,3.64,Copywriting/Drafting,Intermediate,4,False,12.23,1,Allowed_With_Citation,4,4.000,79.59,Low
49952,149953,STEM,Sophomore,2.363,24.45,Debugging/Troubleshooting,Intermediate,4,True,15.02,8,Actively_Encouraged,4,2.753,83.62,High
49953,149954,Humanities,Senior,2.463,4.31,Copywriting/Drafting,Intermediate,2,False,14.72,4,Actively_Encouraged,4,2.684,83.92,Medium
49955,149956,Business,Sophomore,2.098,6.34,Summarizing_Reading,Intermediate,3,False,13.45,2,Allowed_With_Citation,3,2.543,65.84,Low
49957,149958,Business,Freshman,2.584,10.57,Ideation,Intermediate,2,True,19.47,5,Actively_Encouraged,1,2.922,95.88,High
49959,149960,Humanities,Freshman,2.654,1.57,Debugging/Troubleshooting,Intermediate,1,True,16.37,4,Allowed_With_Citation,2,2.918,100.00,Low
49963,149964,Arts,Junior,2.970,0.87,Summarizing_Reading,Intermediate,1,True,6.92,2,Allowed_With_Citation,3,3.331,83.66,Medium
49964,149965,Business,Graduate,3.697,5.22,Ideation,Intermediate,3,True,8.64,4,Allowed_With_Citation,6,3.867,64.73,Medium
49965,149966,Humanities,Sophomore,2.170,12.76,Copywriting/Drafting,Intermediate,1,True,11.09,2,Strict_Ban,8,2.268,60.93,High
49966,149967,Medical,Junior,2.921,22.68,Summarizing_Reading,Advanced,5,True,4.56,7,Allowed_With_Citation,4,3.150,71.18,High
49970,149971,STEM,Freshman,3.219,10.48,Copywriting/Drafting,Intermediate,5,False,8.44,3,Allowed_With_Citation,1,3.343,74.77,Low
49975,149976,Business,Graduate,1.915,22.75,Copywriting/Drafting,Intermediate,3,True,6.10,4,Allowed_With_Citation,6,2.159,48.98,High
49977,149978,Medical,Sophomore,3.836,10.66,Summarizing_Reading,Intermediate,3,False,4.69,6,Actively_Encouraged,1,3.790,75.18,Medium
49978,149979,Business,Sophomore,3.327,12.72,Ideation,Intermediate,3,False,12.96,4,Allowed_With_Citation,4,3.570,65.49,High
49982,149983,Business,Sophomore,3.474,6.68,Direct_Answer_Generation,Intermediate,2,False,7.52,4,Allowed_With_Citation,9,3.507,75.47,Low
49984,149985,Business,Senior,3.548,2.76,Copywriting/Drafting,Advanced,5,False,9.19,3,Allowed_With_Citation,6,3.721,93.32,Low
49987,149988,Humanities,Junior,2.980,0.50,Direct_Answer_Generation,Intermediate,2,False,16.07,4,Allowed_With_Citation,2,3.568,86.06,Low
49989,149990,Business,Sophomore,3.113,22.66,Ideation,Intermediate,3,True,15.54,4,Actively_Encouraged,6,3.521,96.06,High
49990,149991,Business,Senior,2.970,2.63,Summarizing_Reading,Intermediate,2,False,24.95,1,Allowed_With_Citation,1,3.238,84.87,Medium
49991,149992,Humanities,Freshman,2.708,13.34,Copywriting/Drafting,Intermediate,2,False,11.65,4,Allowed_With_Citation,5,2.785,65.24,High
49993,149994,STEM,Sophomore,3.588,25.64,Debugging/Troubleshooting,Intermediate,3,True,4.62,5,Strict_Ban,10,3.841,58.44,High
49996,149997,STEM,Senior,2.870,2.51,Copywriting/Drafting,Intermediate,1,False,4.67,3,Actively_Encouraged,3,3.096,81.62,Medium
49997,149998,Business,Senior,3.177,15.87,Summarizing_Reading,Advanced,5,True,3.92,4,Allowed_With_Citation,5,3.605,97.21,High
49998,149999,Business,Junior,3.398,19.91,Debugging/Troubleshooting,Intermediate,5,False,7.10,5,Allowed_With_Citation,3,3.527,84.12,Medium